const phoneCountryCodes = {
  ["United States and Canada"]: "+1",
  ["United Kingdom"]: "+44",
  ["Australia"]: "+61",
  ["Germany"]: "+49",
  ["France"]: "+33",
  ["Spain"]: "+34",
  ["Italy"]: "+39",
  ["India"]: "+91",
  ["China"]: "+86",
  ["Japan"]: "+81",
  ["Brazil"]: "+55",
  ["Mexico"]: "+52",
  ["South Africa"]: "+27",
  ["Russia"]: "+7",
  ["Saudi Arabia"]: "+966",
  ["United Arab Emirates"]: "+971",
  ["South Korea"]: "+82",
  ["Turkey"]: "+90",
  ["Argentina"]: "+54",
  ["Egypt"]: "+20",
  ["Canada"]: "+1",
  ["New Zealand"]: "+64",
  ["Singapore"]: "+65",
  ["Malaysia"]: "+60",
  ["Indonesia"]: "+62",
  ["Thailand"]: "+66",
  ["Philippines"]: "+63",
  ["Vietnam"]: "+84",
  ["Cambodia"]: "+855",
  ["Laos"]: "+856",
  ["Myanmar (Burma)"]: "+95",
  ["Bangladesh"]: "+880",
  ["Pakistan"]: "+92",
  ["Afghanistan"]: "+93",
  ["Iran"]: "+98",
  ["Iraq"]: "+964",
  ["Israel"]: "+972",
  ["Jordan"]: "+962",
  ["Lebanon"]: "+961",
  ["Kuwait"]: "+965",
  ["Qatar"]: "+974",
  ["Oman"]: "+968",
  ["Bahrain"]: "+973",
  ["Yemen"]: "+967",
  ["Syria"]: "+963",
  ["Cyprus"]: "+357",
  ["Greece"]: "+30",
  ["Romania"]: "+40",
  ["Hungary"]: "+36",
  ["Poland"]: "+48",
  ["Ukraine"]: "+380",
  ["Belarus"]: "+375",
  ["Kazakhstan"]: "+7",
  ["Uzbekistan"]: "+998",
  ["Turkmenistan"]: "+993",
  ["Azerbaijan"]: "+994",
  ["Georgia"]: "+995",
  ["Armenia"]: "+374",
};

export { phoneCountryCodes };
