version: "3.8"

services:
  platfo-front:
    container_name: platfo-front
    domainname: platfo-front
    build:
      context: .
      args:
        BASE_URL: https://api.platfo.net
        FACEBOOK_ID: 448865257100176
    ports:
      - "3000:3000"
    env_file:
      - .env
